# Trigger
sudo: false
language: android
env:
  global:
    - TERM=dumb

android:
  components:
    - build-tools-23.0.0
    - android-23
    - extra-android-support
    - extra-android-m2repository

    # Emulator components
    - sys-img-armeabi-v7a-android-23

  licenses:
    - '.+'

jdk:
  - oraclejdk8

notifications:
  email: false

# Emulator Management: Create, Start and Wait
before_script:
  - cp `which android-wait-for-emulator` .
  - sed -i -e 's/timeout_in_sec=.*/timeout_in_sec=600/' android-wait-for-emulator
  - android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -gpu off &
  - ./android-wait-for-emulator
  - adb shell input keyevent 82 &

#define test scripts here
script:
  - chmod +x ./gradlew
  # disable predexing on build server
  - ./gradlew clean assemble -PdisablePreDex
  # run tests  against the emulator
  - ./gradlew connectedAndroidTest

after_success:
  - echo "Tests finished successfully"

after_script:
  # upload test results to s3 bucket
#  - echo "Uploading test results to https://chaione-app-store.s3.amazonaws.com/android/DrNow/androidTests/connected/index.html"
#  - s3cmd put sync --recursive --acl-private --guess-mime-type --config=../.s3cfg app/build/reports/androidTests/connected s3://chaione-app-store/android/DrNow/androidTests/

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2

