language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - extra-android-m2repository
    - android-22
    # List of Android SDK components
    - addon-google_apis-google-22
    # Emulator components
    - sys-img-armeabi-v7a-addon-google_apis-google-22

jdk:
  - oraclejdk8

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:22" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
#define test scripts here
  - ./app/gradlew build connectedCheck
#  - ./app/gradlew unitTest assemble

#after_success:
#  - .buildscript/deploy_snapshot.sh

after_success:
#upload build to TestDroid or Apkudo